"""Per-topic evidence coverage report: how much evidence backs each of
T1-T6, from how many sources, how fresh, and how much has been reviewed
(vs. just LLM-classified, which is a weaker claim -- see
`.claude/agents/evidence-auditor.md`).
"""

import statistics
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from verityai.evidence.models import EvidenceRecord, ResearchTopic

_TOPICS: tuple[ResearchTopic, ...] = ("T1", "T2", "T3", "T4", "T5", "T6")


def _parse_iso(value: str) -> Optional[datetime]:
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


@dataclass
class TopicCoverage:
    topic: str
    record_count: int
    sources: list[str] = field(default_factory=list)
    validation_pass_rate: Optional[float] = None
    median_age_days: Optional[float] = None
    llm_classified_rate: float = 0.0
    reviewed_rate: float = 0.0


def compute_coverage_report(
    records: list[EvidenceRecord], now: Optional[datetime] = None
) -> list[TopicCoverage]:
    """One `TopicCoverage` per T1-T6 topic, in order, even for topics with
    zero records (an empty topic is itself worth surfacing, not omitting).
    """
    now = now or datetime.now(timezone.utc)
    report = []

    for topic in _TOPICS:
        topic_records = [r for r in records if topic in r.feeds_topics]
        if not topic_records:
            report.append(TopicCoverage(topic=topic, record_count=0))
            continue

        sources: list[str] = sorted({str(r.source) for r in topic_records})
        valid_count = sum(1 for r in topic_records if r.validation.status == "valid")

        ages = []
        for r in topic_records:
            parsed = _parse_iso(r.retrieved_at)
            if parsed is not None:
                ages.append((now - parsed).days)
        median_age = statistics.median(ages) if ages else None

        classified_count = sum(
            1
            for r in topic_records
            if r.classification is not None and r.classification.classified_by != "none"
        )
        reviewed_count = sum(
            1
            for r in topic_records
            if r.classification is not None and r.classification.classification_reviewed
        )

        report.append(
            TopicCoverage(
                topic=topic,
                record_count=len(topic_records),
                sources=sources,
                validation_pass_rate=valid_count / len(topic_records),
                median_age_days=median_age,
                llm_classified_rate=classified_count / len(topic_records),
                reviewed_rate=reviewed_count / len(topic_records),
            )
        )

    return report


def _fmt_pct(value: Optional[float]) -> str:
    return "n/a" if value is None else f"{value * 100:.0f}%"


def _fmt_age(value: Optional[float]) -> str:
    return "n/a" if value is None else f"{value:.0f}d"


def render_markdown(report: list[TopicCoverage]) -> str:
    lines = [
        "# Evidence Coverage Report",
        "",
        "Auto-generated by `scripts/report_evidence_coverage.py`. See "
        "`.claude/agents/evidence-auditor.md` for how to spot-check authenticity "
        "and claim support beyond what this table can show.",
        "",
        "| Topic | Records | Sources | Validation pass rate | Median age | LLM-classified | Reviewed |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in report:
        sources = ", ".join(row.sources) if row.sources else "none"
        lines.append(
            f"| {row.topic} | {row.record_count} | {sources} | "
            f"{_fmt_pct(row.validation_pass_rate)} | {_fmt_age(row.median_age_days)} | "
            f"{_fmt_pct(row.llm_classified_rate)} | {_fmt_pct(row.reviewed_rate)} |"
        )
    lines.append("")
    return "\n".join(lines)
